# AP5/NBQX drug test seeds: top-20 generations (by fitness) from
# batch_2026-04-02_spiking_only, with AMPA + NMDA weights
# (weightEE_AMPA, weightEI_AMPA, weightEE_NMDA, weightEI_NMDA) scaled to 1%
# (glutamate block). Generated by _scripts/make_weight_scaled_top_gens.py.
# Ordered best -> worst fitness.
seeds = [
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_25_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_157_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_146_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_121_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_151_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_55_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_161_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_110_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_154_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_111_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_108_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_102_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_152_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_155_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_144_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_158_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_153_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_156_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_162_ampa_nmda1pct_cfg.json',
    '/pscratch/sd/k/ktub1999/networkSimulations/z_simulated_data/CDKL5_seed_large_limited_tau_2_w1_focus_InhFR/batch_runs/batch_2026-04-02_spiking_only/ampa_nmda_scaled_top_20_1pct/trial_92_ampa_nmda1pct_cfg.json',
]
